#include<stdio.h>
#include<math.h>
#include<iostream>
using namespace std;
int main()
{
  int a[26]={0},b[26]={0},i;
  long long int del=0;
  char s1[10005],s2[10005];
  gets(s1);
  gets(s2);
  for(i=0;s1[i]!='\0';i++)
  {
      if(s1[i]=='a')
      a[0]++;
      if(s1[i]=='b')
      a[1]++;
      if(s1[i]=='c')
      a[2]++;
      if(s1[i]=='d')
      a[3]++;
      if(s1[i]=='e')
      a[4]++;
      if(s1[i]=='f')
      a[5]++;
      if(s1[i]=='g')
      a[6]++;
      if(s1[i]=='h')
      a[7]++;
      if(s1[i]=='i')
      a[8]++;
      if(s1[i]=='j')
      a[9]++;
      if(s1[i]=='k')
      a[10]++;
      if(s1[i]=='l')
      a[11]++;
      if(s1[i]=='m')
      a[12]++;
      if(s1[i]=='n')
      a[13]++;
      if(s1[i]=='o')
      a[14]++;
      if(s1[i]=='p')
      a[15]++;
      if(s1[i]=='q')
      a[16]++;
      if(s1[i]=='r')
      a[17]++;
      if(s1[i]=='s')
      a[18]++;
      if(s1[i]=='t')
      a[19]++;
      if(s1[i]=='u')
      a[20]++;
      if(s1[i]=='v')
      a[21]++;
      if(s1[i]=='w')
      a[22]++;
      if(s1[i]=='x')
      a[23]++;
      if(s1[i]=='y')
      a[24]++;
      if(s1[i]=='z')
      a[25]++;
  }
  for(i=0;s2[i]!='\0';i++)
  {
      if(s2[i]=='a')
      b[0]++;
      if(s2[i]=='b')
      b[1]++;
      if(s2[i]=='c')
      b[2]++;
      if(s2[i]=='d')
      b[3]++;
      if(s2[i]=='e')
      b[4]++;
      if(s2[i]=='f')
      b[5]++;
      if(s2[i]=='g')
      b[6]++;
      if(s2[i]=='h')
      b[7]++;
      if(s2[i]=='i')
      b[8]++;
      if(s2[i]=='j')
      b[9]++;
      if(s2[i]=='k')
      b[10]++;
      if(s2[i]=='l')
      b[11]++;
      if(s2[i]=='m')
      b[12]++;
      if(s2[i]=='n')
      b[13]++;
      if(s2[i]=='o')
      b[14]++;
      if(s2[i]=='p')
      b[15]++;
      if(s2[i]=='q')
      b[16]++;
      if(s2[i]=='r')
      b[17]++;
      if(s2[i]=='s')
      b[18]++;
      if(s2[i]=='t')
      b[19]++;
      if(s2[i]=='u')
      b[20]++;
      if(s2[i]=='v')
      b[21]++;
      if(s2[i]=='w')
      b[22]++;
      if(s2[i]=='x')
      b[23]++;
      if(s2[i]=='y')
      b[24]++;
      if(s2[i]=='z')
      b[25]++;
  }
 for(i=0;i<26;i++)
 {
     del=del+fabs(a[i]-b[i]);
 }
 cout<<del;
}
